//! Create an OFD document with text, images, and paths, then write to disk.
//!
//! Usage:
//!   cargo run --release --example write_simple
//!
//! Produces `output.ofd` in the current directory.

use easyofd::{EasyOfd, ImageObject, OfdPage, PathObject, TextObject};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let output_path = "output.ofd";

    // --- Page 1: title + body + horizontal rule ---
    let mut page1 = OfdPage::new(210.0, 297.0); // A4
    page1.add_text(
        TextObject::new(20.0, 30.0, "easyofd-rust Demo Document")
            .size(24.0)
            .bold(),
    );
    page1.add_text(TextObject::new(
        20.0,
        60.0,
        "This OFD was generated by the write_simple example.",
    ));
    page1.add_path(PathObject::hline(20.0, 75.0, 190.0));
    page1.add_text(TextObject::new(
        20.0,
        90.0,
        "OFD (Open Fixed-layout Document) is the Chinese national standard \
         GB/T 33190-2016 for fixed-layout documents.",
    ));

    // --- Page 2: text + image + rectangle ---
    let mut page2 = OfdPage::new(210.0, 297.0);
    page2.add_text(
        TextObject::new(20.0, 30.0, "Page Two -- Mixed Content")
            .size(18.0)
            .bold(),
    );
    // Embed a small placeholder JPEG image (invalid data, but demonstrates the API).
    let placeholder_jpeg = vec![0xFF, 0xD8, 0xFF, 0xE0, 0x00, 0x10];
    page2.add_image(ImageObject::jpeg(20.0, 60.0, 50.0, 50.0, placeholder_jpeg));
    page2.add_text(TextObject::new(
        80.0,
        80.0,
        "Image placeholder embedded above.",
    ));
    page2.add_path(PathObject::rect(20.0, 130.0, 170.0, 60.0));

    // Write using the fluent builder with metadata.
    EasyOfd::write_pages(output_path)
        .metadata_title("easyofd-rust Demo")
        .metadata_author("easyofd-rust")
        .metadata_creator("write_simple example")
        .do_write(vec![page1, page2])?;

    println!("Wrote OFD to: {output_path}");
    let bytes = std::fs::read(output_path)?;
    println!("File size: {} bytes", bytes.len());

    // Clean up.
    let _ = std::fs::remove_file(output_path);
    Ok(())
}
